production:
  password: 
  theme_id: "64267077"
  store: the-gld-shop.myshopify.com
  timeout: 30s
  ignore_files:
    - "*.gif"
    - "*.jpg"
    - "*.png"
    - "*.svg"
    - "*.eot"
    - "*.tff"
    - "*.ttf"
    - "*.otf"
    - "*.woff"
    - config/settings_data.json
development:
  password:
  theme_id: "149887881"
  store: the-gld-shop.myshopify.com
  timeout: 30s
  ignore_files:
    - "*.gif"
    - "*.jpg"
    - "*.png"
    - "*.svg"
    - "*.eot"
    - "*.tff"
    - "*.ttf"
    - "*.otf"
    - "*.woff"
    - config/settings_data.json